
export const SET_FILES_RECEIVED = 'SET_FILES_RECEIVED';

export const SET_PREVIEW_ID = 'SET_PREVIEW_ID';
export const SET_LAST_POLL_TIME = 'SET_LAST_POLL_TIME';
export const RESTORE_PREVIEW = 'RESTORE_PREVIEW';
export const ADD_PREVIEW = 'ADD_PREVIEW';
export const SET_PREVIEW_STATUS = 'SET_PREVIEW_STATUS';
export const SET_PREVIEW_TIMESTAMP = 'SET_PREVIEW_TIMESTAMP';
export const SET_PREVIEW_FILES = 'SET_PREVIEW_FILES';

export const SET_PARAMS = 'SET_PARAMS';
export const SET_PARAM = 'SET_PARAM';
export const SET_OPTIONS = 'SET_OPTIONS';

export const RESET_UI = 'RESET_UI';
export const RESET_PREVIEW = 'RESET_PREVIEW';
export const SET_ERROR = 'SET_ERROR';
export const RESET_ERROR = 'RESET_ERROR';

export const SET_USERFIELD = 'SET_USERFIELD';
